from . import res_users
from . import product_template
from . import stock_location
from . import stock_location_log
from . import res_partner
from . import sale_order
from . import crm_lead
from . import sale_subscription
from . import pos
from . import res_company
from . import sign
from . import product_category